name: ws

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  loggy: ^2.0.3
  obs_websocket:
    path: ../
  universal_io: ^2.2.2
  web_socket_channel: ^2.4.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
