name: obs_websocket
version: 5.0.0+9
homepage: https://github.com/faithoflifedev/easy_obs_websocket
description: obs_websocket allows dart-based connections to the OBS (Open Broadcaster Software) plugin obs-websocket
repository: https://github.com/faithoflifedev/easy_obs_websocket
environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  args: ^2.3.1
  crypto: ^3.0.2
  json_annotation: ^4.6.0
  loggy: ^2.0.1+1
  uuid: ^3.0.6
  universal_io: ^2.0.4
  validators: ^3.0.0
  web_socket_channel: ^2.2.0
  yaml: ^3.1.1
dev_dependencies:
  build_runner: ^2.2.0
  grinder: ^0.9.2
  http: ^0.13.5
  json_serializable: ^6.3.1
  lints: ^2.0.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  process_run: ^0.12.3+2
  pub_semver: ^2.1.1
  pubspec: ^2.3.0
  test: ^1.21.4

  publish_tools: ^0.1.0+3
executables:
  obs:
