name: obs_websocket
version: 5.1.0+1
homepage: https://github.com/faithoflifedev/easy_obs_websocket
description: obs_websocket allows dart-based connections to the OBS (Open Broadcaster Software) plugin obs-websocket
repository: https://github.com/faithoflifedev/easy_obs_websocket
environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  args: ^2.4.0
  crypto: ^3.0.2
  json_annotation: ^4.8.0
  loggy: ^2.0.3
  uuid: ^3.0.7
  universal_io: ^2.2.0
  validators: ^3.0.0
  web_socket_channel: ^2.3.0
  yaml: ^3.1.1
dev_dependencies:
  build_runner: ^2.3.3
  grinder: ^0.9.3
  http: ^0.13.5
  json_serializable: ^6.6.1
  lints: ^2.0.1
  mustache_template: ^2.0.0
  path: ^1.8.3
  process_run: ^0.12.5+2
  pub_semver: ^2.1.3
  pubspec: ^2.3.0
  test: ^1.23.1

  publish_tools: ^0.1.0+10
  # publish_tools:
  #   path: ../../publish_tools
executables:
  obs:
